@startuml user-authentication-sequence-diagram
actor User
box "Client" #LightGreen
participant "Frontend" as FE
end box
box "Backend" #LightBlue
participant "Server API" as Server_API
participant "Data Processor" as DP
end box
database "Database" as DB

User -> FE: Inputs name, email, username, and password
activate FE
FE -> Server_API: Send user details
activate Server_API
Server_API -> DP: Validate user input
activate DP
alt Invalid user input
DP --> Server_API: Send validation result
Server_API --> FE: Forward validation result
deactivate Server_API
FE --> User: Display account creation failure message
deactivate FE

else Valid user input
DP -> DB: Store user details
activate DB
DB --> DP: Confirm storage
deactivate DB
DP --> Server_API: Send validation result
deactivate DP
activate Server_API
Server_API --> FE: Forward validation result
deactivate Server_API
activate FE
FE --> User: Display account creation success message
deactivate FE
end

@enduml