@startuml
actor        Device as device
box "backend" #LightBlue
participant  Sensor_Module_API as sensor_API
participant  Data_Ingest_Processor as data_processor
end box
database     Database as database

device -> sensor_API: send datalog (audio, temperature, motion, light, humidity)
sensor_API -> data_processor: receive data
data_processor -> database: processes data & stores in database

@enduml