@startuml user-authentication-activity-diagram
start

if (Existing user?) then (Yes)
repeat
    :User inputs username and password;
    :Authenticate credentials;
repeat while (Are credentials valid?) is (no) not (yes)
:Grant access to the system;
else (No)
repeat
    :User inputs name, email, username and password;
    :Authenticate user details;
    repeat while (Is user input valid?) is (no) not (yes)
        :Store user details in database;
        :Display success message;
endif

stop
@enduml