@startuml
start

:User selects date and animal type filters;
:Send date and animal type filter request to Backend;

if (Backend Response) then (Returns processed data)
    :Display data visualisation to User;
else (Return Error Message)
    :Show empty data visualisation to User;
endif

stop
@enduml
