@startuml

actor User
box "FrontEnd" #LightGreen
entity "Device Map Page" as UI
endbox

box "BackEnd" #LightBlue
entity "Server_API" as Server
entity "Map API" as MapAPI
entity "Data Retrieval Processor" as Processor
endbox 

database "Database" as DB


User -> UI: Open Device Map Page
UI -> MapAPI: Request map data
MapAPI --> UI: Return map data

UI -> Server: Request sensor data  from specificed location
Server -> Processor: Process sensor data request
Processor -> DB: Fetch sensor data
DB --> Processor: Return sensor data
Processor --> Server: Send processed data
Server --> UI: Send sensor data (location, description, status and last update)

alt Devices Available
    UI -> User: Render map with sensors
else No Devices Available
    UI -> User: Render empty map
end

User -> UI: Clicks on a sensor marker
UI --> User: Highlights the sensor in the table

User -> UI: Selects the sensors
User -> UI: Selects export data or export audio and selects the date range
UI -> Server: Request data export of the selected devices within the date range
Server -> Processor: Process export request
Processor -> DB: Fetch export data
DB --> Processor: Return export data
Processor --> Server: Send processed export data
Server --> UI: Provide file
UI --> User: Prompt file download

@enduml
