# Generated by Django 5.1.6 on 2025-02-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="latitude",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="device",
            name="longditude",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="device",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
