# Generated by Django 5.1.6 on 2025-02-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0002_device_latitude_device_longditude_device_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="longditude",
        ),
        migrations.AddField(
            model_name="device",
            name="longitude",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                max_length=8,
            ),
        ),
    ]
