# Generated by Django 5.1.6 on 2025-02-24 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0004_rename_longitude_device_longditude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="longditude",
        ),
        migrations.AddField(
            model_name="device",
            name="longitude",
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="DataLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(null=True)),
                ("data", models.CharField(max_length=255, null=True)),
                ("metadata", models.CharField(max_length=255, null=True)),
                (
                    "sensorType",
                    models.CharField(
                        choices=[("audio", "audio")], default="audio", max_length=50
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="devices.device"
                    ),
                ),
            ],
        ),
    ]
