# Generated by Django 5.1.6 on 2025-02-24 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0005_remove_device_longditude_device_longitude_datalog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="longitude",
            new_name="longditude",
        ),
    ]
