# Generated by Django 5.1.6 on 2025-03-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_rename_longitude_device_longditude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
