# Generated by Django 5.1.6 on 2025-03-17 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
