# Generated by Django 5.1.6 on 2025-03-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_datalog_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalog',
            options={'verbose_name': 'Data Log', 'verbose_name_plural': 'Data Logs'},
        ),
        migrations.AlterField(
            model_name='device',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='longditude',
            field=models.FloatField(default=0),
        ),
    ]
