# Generated by Django 5.1.6 on 2025-03-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_datalog_options_alter_device_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='latitude',
            field=models.FloatField(default=1.390881),
        ),
        migrations.AlterField(
            model_name='device',
            name='longditude',
            field=models.FloatField(default=103.817027),
        ),
    ]
