@startuml software-architecture-diagram

' Define layout hints for better arrangement
skinparam linetype polyline
skinparam componentStyle rectangle
' Define packages for Frontend, Backend, and Hardware Device
package "Frontend" #LightGreen {
    component "**API Client Module**" as FrontendApiClient
    component "**Data Visualization Module**\n*Charts and Graphs\n*Table View\n*Export Data" as FrontendDataVis
    component "**Maps**\n*Device Information\n*Birds Information" as FrontendMaps
    component "**User Authentication Module**" as FrontendAuth
    component "**Map Module**\nGenerates map" as FrontendMap
}

package "Backend" #LightBlue {
    component "**API Server Module**" as BackendApiServer
    component "**User Authentication Module**" as BackendAuth
    component "**Data Ingestion Processor**\n*Stores raw data to Data Lake\n*Extract metadata to Postgres" as BackendIngest
    component "**Data Cleaning Processor**" as BackendCleaning
    component "**Data Transformation Processor**\n*Make data ready for analysis" as BackendTransformation
    component "**Data Retrieval Processor**" as BackendRetrieval
}

package "Data Analysis" #LightYellow {
    component "**Data Preprocessing**\n*Make data ready for input" as DataPreprocessing
    component "**Machine Learning Models**" as MLModels
    component "**Data Postprocessing**\n*Format and filter results" as Postprocessing
}

' Define external services
component "**External Maps API**" as MapsAPI
database "**PostgreSQL Database**\n*Structued Data\n*Metadata\n*User Data" as PGDB
database "**Data Lake**\n*Raw Data\n*Intermediate Data" as DataLake

' Define relationships
' Frontend to Backend
FrontendApiClient <--> BackendApiServer
FrontendDataVis --> FrontendApiClient
FrontendMaps --> FrontendApiClient
FrontendAuth --> FrontendApiClient
FrontendMap --> MapsAPI

' Backend Pipeline
BackendApiServer --> BackendAuth
BackendApiServer --> BackendIngest
BackendIngest --> DataLake
BackendIngest --> PGDB
BackendAuth --> PGDB
BackendIngest --> BackendCleaning
BackendCleaning --> DataLake
BackendCleaning --> BackendTransformation
BackendTransformation --> DataLake
BackendTransformation --> DataPreprocessing

'ML pipeline
DataPreprocessing --> MLModels
MLModels --> Postprocessing
Postprocessing --> DataLake
Postprocessing --> PGDB

' Retrieve data
PGDB --> BackendRetrieval
BackendRetrieval --> BackendApiServer

' better layout
left to right direction
BackendApiServer -[hidden]-> BackendCleaning
BackendApiServer -[hidden]-> BackendTransformation
BackendApiServer -[hidden]-> BackendRetrieval

@enduml
