# Generated by Django 5.1.6 on 2025-03-28 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='birdName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonName', models.CharField(max_length=100)),
                ('speciesCode', models.CharField(max_length=100)),
                ('environment', models.CharField(choices=[('urban', 'Urban'), ('forest', 'Forest'), ('other', 'Other')], default='other', max_length=50)),
                ('priority', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='birdLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, null=True)),
                ('beginTime', models.DateTimeField()),
                ('timeOffset', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('confidence', models.FloatField()),
                ('birdName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='birds.birdname')),
            ],
            options={
                'verbose_name': 'Bird Log',
                'verbose_name_plural': 'Bird Logs',
            },
        ),
    ]
