# Generated by Django 5.1.6 on 2025-03-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='birdName',
            new_name='birds',
        ),
        migrations.AlterModelOptions(
            name='birds',
            options={'verbose_name': 'Birds', 'verbose_name_plural': 'Birds'},
        ),
    ]
