# Generated by Django 5.1.6 on 2025-03-28 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_rename_birdname_birds_alter_birds_options'),
        ('devices', '0011_alter_device_id_alter_device_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birdlog',
            old_name='birdName',
            new_name='speciesCode',
        ),
        migrations.AddField(
            model_name='birdlog',
            name='deviceId',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.PROTECT, to='devices.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birds',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
