# Generated by Django 5.1.6 on 2025-03-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_rename_birdname_birdlog_speciescode_birdlog_deviceid_and_more'),
        ('devices', '0011_alter_device_id_alter_device_latitude_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='birdlog',
            unique_together={('speciesCode', 'deviceId', 'timestamp')},
        ),
    ]
