# Generated by Django 5.1.6 on 2025-04-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_alter_birdlog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birds',
            name='speciesCode',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
