@startuml alert-management-activity-diagram
start

:Receive data from device;

:Apply alert conditions logic to classify data;

if (Is data classified as alert?) then (yes)
    :Store data and alert in database;
    
    :Send alert notification to frontend;

else (no)
    :store data in database;
endif
stop

@enduml
